config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :likes
    resources :comments
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_post

    def new
        @comment = Comment.new
    end

    def create
        # @comment = @post.comments.build(comment_params)
        # @comment.user_id = current_user.id

        @comment = @post.comments.new(comment_params)
        @comment.user_id = current_user.id
        
        @comment.save
        
        redirect_to post_path(@post)
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:text)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]


    def create
        if already_liked?
        flash[:notice] = "You can't like more than once"
        else
        @post.likes.create(user_id: current_user.id)
        end
        redirect_to root_path
    end

    def destroy
        if !(already_liked?)
        flash[:notice] = "Cannot unlike"
        else
        @like.destroy
        end
        redirect_to root_path
    end

    private

    def find_post
        @post = Post.find(params[:post_id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, post_id:
        params[:post_id]).exists?
    end

    def find_like
        @like = @post.likes.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @users = User.all
    @post = current_user.posts.build
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:text)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= simple_form_for [ @post, @comment ] do |f| %>
  <p>
    <%= f.input :text %><br/>
  </p>
  <p>
    <%= f.button :submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'%>
  </head>

  <body>
    <nav class="nav">
      <ul class='list'>

        <div class='left'>
          <li class='navBar'> 
            <h1> <%= link_to 'Facebook', root_path, class:'navBar Facebook' %> </h1> 
          </li>
        </div>

        <% if user_signed_in? %>
          <div class='right'> 
            <li class='navBar right'> <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'navBar' %> </li>
          </div>
        <% end %>

      </ul>
    </nav>
    <div class='all'>
    <% if flash[:notice] %>
      <div class="notification is-primary">
        <p class="notice"> <%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"> <%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/likes/show.html.erb
<%= button_to 'Like', post_likes_path(@post), method: :post %>

app/views/posts/_comment.html.erb
<div class='comment'>
  <% if comment.user.username == current_user.username %>
    <h3 class='self-name'> Your Comment </h3>
  <% else %>
    <h3> <%= comment.user.username %> </h3>
  <% end %>
  <p><%= comment.text %></p>
  <% if comment.user.username == current_user.username %>
    <%= link_to [ @post, comment ], method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class='fa fa-trash' aria-hidden='true'> </i>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_form1.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :text, autocomplete: 'off', autofocus: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form1', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class='front'>
  <div class='profile'>
    <h1> Your Profile </h1>
    <div class='post profiles'>
      <div class='name_and_picture'> 
        <%= image_tag("example.jpg", :alt => "rss feed", class:'img') %>
        <span class='prof_name na'><%= current_user.name %></span>
        <%= link_to 'users/edit' do %>
          <i class='prof_name fa fa-pencil' aria-hidden='true'> </i> 
        <% end %>
      </div> <br> <br>
      <span class='un'><%= current_user.username %></span> <br>
      <span class='em'><%= current_user.email %></span> <br>
      
    </div> <br>
    <h1> Your Friends </h1>
    <div class='post'>
    
    </div>
  </div>

  <div class='index'>
    <h1>Posts</h1>

    <div class='post'>
      <h3 class='name self-name'> Write A New Post </h3>
      <%= render 'form1', post: @post %>
    </div>
    <% @posts.each do |post| %>
      <div class='post'>
        <% if post.user.username == current_user.username %>
          <h3 class='name self-name'> You </h3>
        <% else %>
          <h3 class='name'> <%= post.user.username %> </h3>
        <% end %>
            
        <p class='text'><%= post.text %></p>
            
        <p class='control'>

          <%= link_to post do %>
            <i class='fa fa-link' aria-hidden='true'> </i>
          <% end %>

          <% if post.user.username == current_user.username %>
            <%= link_to edit_post_path(post) do %>
              <i class='fa fa-pencil' aria-hidden='true'> </i>
            <% end %>
            <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class='fa fa-trash' aria-hidden='true'> </i>
            <% end %>
          <% end %>
          
          <%= post.likes.count %> 

          <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= link_to post_like_path(post, pre_like), method: :delete do %>
              <i class='fa fa-heart' aria-hidden='true'> </i>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(post), method: :post do %>
              <i class='fa fa-heart-o' aria-hidden='true'> </i>
            <% end %>
          <% end %>
          
        </p>
      </div>
    <% end %>

  <br>

  <%= link_to 'New Post', new_post_path %>
  </div>

  <div class='follow'>
    <h1> Who to Follow </h1>
    <% @users.each do |user| %>
      <% if current_user.username != user.username %>
        <div class='post followers'>
          <span class='na'><%= user.name %></span> <br>
          <span class='un'><%= user.username %></span> <br>
          <span class='em'><%= user.email %></span> <br>
        </div>
      <%end%>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class='post show'>

<% if @post.user.username == current_user.username %>
  <h3 class='name self-name'> You </h3>
<% else %>
  <h3 class='name'> <%= @post.user.username %> </h3>
<% end %>

<p>
  <%= @post.text %>
</p>

<% if current_user.username == @post.user.username %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %> <br>

<%= @post.likes.count %> 

<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= link_to post_like_path(@post, pre_like), method: :delete do %>
    <i class='fa fa-heart' aria-hidden='true'> </i>
  <% end %>
<% else %>
  <%= link_to post_likes_path(@post), method: :post do %>
    <i class='fa fa-heart-o' aria-hidden='true'> </i>
  <% end %>
<% end %>

</div>

<br>

<h3> <%= @post.comments.count %> <%= (@post.comments.count) == 1 ? 'Comment' : 'Comments'%> </h3>

<%= render partial: 'comments/form' %>

<%= render partial: 'posts/comment', collection: @post.comments %>